# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 263408aa8dbf7f023bb5726e280fce321ec3f917dd23954750fbab976302f052b009f385c65cb7c9d0f1195388089db4c5692309f2a61684af6829e778eecd55

test:
  secret_key_base: 3723afc6abfe2bb561fdabc5a65aab08240d6b4b86265e6ae37f1a3d044e47b4ad7bb3605949a9b032ee4ad170571960a6a73aca03aeaabdc2bfa91569ebc6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
